services:
  db:
    image: postgres:latest
    container_name: dispensa-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dispensa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped



volumes:
  postgres_data: